# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9680107f5e3b8c9b1811d1fa9231c9017726c68ad6a8901cf7e6cccdca2f7d41327dc07e15bc640dd100aecb78033a9ac25f828de37a8881e7e1023bdd453c43

test:
  secret_key_base: f841ccc8921747577ab3c5872c6b869a84c22e740ebcc024b0f76ffca2971bfd056c419edc799adbaa69b6d354d19515a4eb53cb8242185c2469d6aadd37c669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
